apiVersion: v1
kind: ConfigMap
metadata:
  name: swe-auth-service-configmap
  namespace: swe-prod
data:
  APP_NAME: "swe-auth"
  ENV: "prod"
  DB_NAME: "SweAuth"
  DB_SEARCH_PATH: "sweauth"
  DB_SSL_MODE: "require"
  GRPC_PORT: "7020"
  JWT_EXPIRATION: "3600"
  REFRESH_TOKEN_EXPIRATION: "7200"
  KAFKA_BROKERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"