apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe-auth-service
  namespace: swe-prod
  labels:
    app: swe-auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swe-auth-service
  template:
    metadata:
      labels:
        app: swe-auth-service
    spec:
      containers:
        - name: swe-auth-service
          image: 01092002/swe-auth-service:
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: swe-auth-service-configmap
          ports:
            - containerPort: 7020
---
apiVersion: v1
kind: Service
metadata:
  name: swe-auth-service
  namespace: swe-prod
spec:
  type: NodePort
  selector:
    app: swe-auth-service
  ports:
    - name: grpc
      port: 7020
      targetPort: 7020