apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe-task-service
  namespace: swe-prod
  labels:
    app: swe-task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swe-task-service
  template:
    metadata:
      labels:
        app: swe-task-service
    spec:
      containers:
        - name: swe-task-service
          image: 01092002/swe-task-service:main-1d55bd1-20241211114854
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: swe-task-service-configmap
          ports:
            - containerPort: 7010
---
apiVersion: v1
kind: Service
metadata:
  name: swe-task-service
  namespace: swe-prod
  labels:
    app: swe-task-service
spec:
  type: NodePort
  selector:
    app: swe-task-service
  ports:
    - name: grpc
      port: 7010
      targetPort: 7010