apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe-workflow-service
  namespace: swe-prod
  labels:
    app: swe-workflow-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swe-workflow-service
  template:
    metadata:
      labels:
        app: swe-workflow-service
    spec:
      containers:
        - name: swe-workflow-service
          image: 01092002/swe-workflow-service:main-23ac34e-20250511150128
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: swe-workflow-service-configmap
          ports:
            - containerPort: 7050
---
apiVersion: v1
kind: Service
metadata:
  name: swe-workflow-service
  namespace: swe-prod
  labels:
    app: swe-workflow-service
spec:
  type: NodePort
  selector:
    app: swe-workflow-service
  ports:
    - name: grpc
      port: 7060
      targetPort: 7060