apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe-storage-service
  namespace: swe-prod
  labels:
    app: swe-storage-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swe-storage-service
  template:
    metadata:
      labels:
        app: swe-storage-service
    spec:
      containers:
        - name: swe-storage-service
          image: 01092002/swe-storage-service:main-bf7a895-20241211104659
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: swe-storage-service-configmap
          ports:
            - containerPort: 7030
---
apiVersion: v1
kind: Service
metadata:
  name: swe-storage-service
  namespace: swe-prod
  labels:
    app: swe-storage-service
spec:
  type: NodePort
  selector:
    app: swe-storage-service
  ports:
    - name: grpc
      port: 7030
      targetPort: 7030