apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe-notification-service
  namespace: swe-prod
  labels:
    app: swe-notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swe-notification-service
  template:
    metadata:
      labels:
        app: swe-notification-service
    spec:
      containers:
        - name: swe-notification-service
          image: 01092002/swe-notification-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: swe-notification-service-configmap
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: swe-notification-service
  namespace: swe-prod
  labels:
    app: swe-notification-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: swe-notification-service