apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe-gateway-service
  labels:
    app: swe-gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swe-gateway-service
  template:
    metadata:
      labels:
        app: swe-gateway-service
    spec:
      containers:
        - name: swe-gateway-service
          image: 01092002/swe-gateway-service:latest
          imagePullPolicy: Always
          env:
            - name: K8S_ENV
              value: "prod"
          envFrom:
            - configMapRef:
                name: swe-gateway-service-configmap
          ports:
            - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: swe-gateway-service
spec:
  type: NodePort
  selector:
    app: swe-gateway-service
  ports:
    - name: http
      port: 7777
      targetPort: 7777