apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe-app
  namespace: swe-prod
  labels:
    app: swe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swe-app
  template:
    metadata:
      labels:
        app: swe-app
    spec:
      containers:
        - name: swe-app
          image: 01092002/swe-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: swe-app
  namespace: swe-prod
spec:
  type: NodePort
  selector:
    app: swe-app
  ports:
    - name: http
      port: 80
      targetPort: 80